### ISSUE TITLE
Tests fail unless upgrade MooseX::StrictConstructor

### ISSUE THREAD

**Issue by hashbangperl** [bobtfish/text-multimarkdown#15]
t/markup/standard/unbalanced.t ........ The method '_generate_BUILDALL' was not found in the inheritance hierarchy for Moose::Meta::Class::__ANON__::SERIAL::2 at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Class/MOP/Class.pm line 1053
        Class::MOP::Class::**ANON**('Moose::Meta::Class=HASH(0x166de80)', '_generate_BUILDALL') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Class/MOP/Class.pm line 1098
        Class::MOP::Class::add_around_method_modifier('Moose::Meta::Class=HASH(0x166de80)', '_generate_BUILDALL', 'CODE(0x166b198)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role/Application/ToClass.pm line 231
        Moose::Meta::Role::Application::ToClass::apply_method_modifiers('Moose::Meta::Role::Application::ToClass=HASH(0x166dc88)', 'around', 'Moose::Meta::Role=HASH(0x166abb0)', 'Moose::Meta::Class=HASH(0x166de80)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role/Application.pm line 78
        Moose::Meta::Role::Application::apply_around_method_modifiers('Moose::Meta::Role::Application::ToClass=HASH(0x166dc88)', 'Moose::Meta::Role=HASH(0x166abb0)', 'Moose::Meta::Class=HASH(0x166de80)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role/Application.pm line 64
        Moose::Meta::Role::Application::apply('Moose::Meta::Role::Application::ToClass=HASH(0x166dc88)', 'Moose::Meta::Role=HASH(0x166abb0)', 'Moose::Meta::Class=HASH(0x166de80)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role/Application/ToClass.pm line 36
        Moose::Meta::Role::Application::ToClass::apply('Moose::Meta::Role::Application::ToClass=HASH(0x166dc88)', 'Moose::Meta::Role=HASH(0x166abb0)', 'Moose::Meta::Class=HASH(0x166de80)', 'HASH(0x154a9e8)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role.pm line 470
        Moose::Meta::Role::apply('Moose::Meta::Role=HASH(0x166abb0)', 'Moose::Meta::Class=HASH(0x166de80)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util.pm line 160
        Moose::Util::_apply_all_roles('Moose::Meta::Class=HASH(0x166de80)', undef, 'MooseX::StrictConstructor::Role::Meta::Method::Constructor') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util.pm line 99
        Moose::Util::apply_all_roles('Moose::Meta::Class=HASH(0x166de80)', 'MooseX::StrictConstructor::Role::Meta::Method::Constructor') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Class.pm line 104
        Moose::Meta::Class::create('Moose::Meta::Class', 'Moose::Meta::Class::__ANON__::SERIAL::2', 'roles', 'ARRAY(0x1606b70)', 'weaken', '', 'superclasses', 'ARRAY(0x165ca28)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Class/MOP/Package.pm line 120
        Class::MOP::Package::create_anon('Moose::Meta::Class', 'superclasses', 'ARRAY(0x165ca28)', 'roles', 'ARRAY(0x1606b70)', 'cache', 1) called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Class/MOP/Class.pm line 474
        Class::MOP::Class::create_anon_class('Moose::Meta::Class', 'superclasses', 'ARRAY(0x165ca28)', 'roles', 'ARRAY(0x1606b70)', 'cache', 1) called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util/MetaRole.pm line 134
        Moose::Util::MetaRole::_make_new_class('Moose::Meta::Method::Constructor', 'ARRAY(0x1606b70)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util/MetaRole.pm line 95
        Moose::Util::MetaRole::_make_new_metaclass('Moose::Meta::Class=HASH(0x1655b70)', 'HASH(0x1655768)', 'class') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util/MetaRole.pm line 28
        Moose::Util::MetaRole::apply_metaroles('for', 'Markdent::Event::StartDocument', 'class_metaroles', 'HASH(0x1655768)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Exporter.pm line 641
        Moose::Exporter::__ANON__('MooseX::StrictConstructor', 'for_class', 'Markdent::Event::StartDocument', 'metaclass', undef, 'meta_name', 'meta') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Exporter.pm line 435
        Moose::Exporter::**ANON**('MooseX::StrictConstructor') called at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Event/StartDocument.pm line 11
        Markdent::Event::StartDocument::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        require Markdent/Event/StartDocument.pm called at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Dialect/Standard/BlockParser.pm line 10
        Markdent::Dialect::Standard::BlockParser::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        require Markdent/Dialect/Standard/BlockParser.pm called at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Parser.pm line 10
        Markdent::Parser::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        require Markdent/Parser.pm called at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Test/Markdent.pm line 19
        Test::Markdent::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        require Test/Markdent.pm called at t/markup/standard/unbalanced.t line 8
        main::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
BEGIN failed--compilation aborted at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Event/StartDocument.pm line 11.
Compilation failed in require at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Dialect/Standard/BlockParser.pm line 10.
BEGIN failed--compilation aborted at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Dialect/Standard/BlockParser.pm line 10.
Compilation failed in require at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Parser.pm line 10.
BEGIN failed--compilation aborted at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Parser.pm line 10.
Compilation failed in require at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Test/Markdent.pm line 19.
BEGIN failed--compilation aborted at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Test/Markdent.pm line 19.
Compilation failed in require at t/markup/standard/unbalanced.t line 8.
BEGIN failed--compilation aborted at t/markup/standard/unbalanced.t line 8.
t/markup/standard/unbalanced.t ........ Dubious, test returned 9 (wstat 2304, 0x900)
No subtests run 
t/markup/theory/big-table.t ........... The method '_generate_BUILDALL' was not found in the inheritance hierarchy for Moose::Meta::Class::__ANON__::SERIAL::2 at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Class/MOP/Class.pm line 1053
        Class::MOP::Class::**ANON**('Moose::Meta::Class=HASH(0x1674818)', '_generate_BUILDALL') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Class/MOP/Class.pm line 1098
        Class::MOP::Class::add_around_method_modifier('Moose::Meta::Class=HASH(0x1674818)', '_generate_BUILDALL', 'CODE(0x166ae98)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role/Application/ToClass.pm line 231
        Moose::Meta::Role::Application::ToClass::apply_method_modifiers('Moose::Meta::Role::Application::ToClass=HASH(0x166cfb8)', 'around', 'Moose::Meta::Role=HASH(0x166a8b0)', 'Moose::Meta::Class=HASH(0x1674818)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role/Application.pm line 78
        Moose::Meta::Role::Application::apply_around_method_modifiers('Moose::Meta::Role::Application::ToClass=HASH(0x166cfb8)', 'Moose::Meta::Role=HASH(0x166a8b0)', 'Moose::Meta::Class=HASH(0x1674818)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role/Application.pm line 64
        Moose::Meta::Role::Application::apply('Moose::Meta::Role::Application::ToClass=HASH(0x166cfb8)', 'Moose::Meta::Role=HASH(0x166a8b0)', 'Moose::Meta::Class=HASH(0x1674818)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role/Application/ToClass.pm line 36
        Moose::Meta::Role::Application::ToClass::apply('Moose::Meta::Role::Application::ToClass=HASH(0x166cfb8)', 'Moose::Meta::Role=HASH(0x166a8b0)', 'Moose::Meta::Class=HASH(0x1674818)', 'HASH(0x1549fa8)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Role.pm line 470
        Moose::Meta::Role::apply('Moose::Meta::Role=HASH(0x166a8b0)', 'Moose::Meta::Class=HASH(0x1674818)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util.pm line 160
        Moose::Util::_apply_all_roles('Moose::Meta::Class=HASH(0x1674818)', undef, 'MooseX::StrictConstructor::Role::Meta::Method::Constructor') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util.pm line 99
        Moose::Util::apply_all_roles('Moose::Meta::Class=HASH(0x1674818)', 'MooseX::StrictConstructor::Role::Meta::Method::Constructor') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Meta/Class.pm line 104
        Moose::Meta::Class::create('Moose::Meta::Class', 'Moose::Meta::Class::__ANON__::SERIAL::2', 'roles', 'ARRAY(0x1605490)', 'weaken', '', 'superclasses', 'ARRAY(0x165c118)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Class/MOP/Package.pm line 120
        Class::MOP::Package::create_anon('Moose::Meta::Class', 'superclasses', 'ARRAY(0x165c118)', 'roles', 'ARRAY(0x1605490)', 'cache', 1) called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Class/MOP/Class.pm line 474
        Class::MOP::Class::create_anon_class('Moose::Meta::Class', 'superclasses', 'ARRAY(0x165c118)', 'roles', 'ARRAY(0x1605490)', 'cache', 1) called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util/MetaRole.pm line 134
        Moose::Util::MetaRole::_make_new_class('Moose::Meta::Method::Constructor', 'ARRAY(0x1605490)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util/MetaRole.pm line 95
        Moose::Util::MetaRole::_make_new_metaclass('Moose::Meta::Class=HASH(0xfb0948)', 'HASH(0x1654208)', 'class') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Util/MetaRole.pm line 28
        Moose::Util::MetaRole::apply_metaroles('for', 'Markdent::Event::StartDocument', 'class_metaroles', 'HASH(0x1654208)') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Exporter.pm line 641
        Moose::Exporter::__ANON__('MooseX::StrictConstructor', 'for_class', 'Markdent::Event::StartDocument', 'metaclass', undef, 'meta_name', 'meta') called at /usr/local/lib/perl5/site_perl/5.10.0/x86_64-linux/Moose/Exporter.pm line 435
        Moose::Exporter::**ANON**('MooseX::StrictConstructor') called at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Event/StartDocument.pm line 11
        Markdent::Event::StartDocument::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        require Markdent/Event/StartDocument.pm called at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Dialect/Standard/BlockParser.pm line 10
        Markdent::Dialect::Standard::BlockParser::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        require Markdent/Dialect/Standard/BlockParser.pm called at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Parser.pm line 10
        Markdent::Parser::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        require Markdent/Parser.pm called at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Test/Markdent.pm line 19
        Test::Markdent::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        require Test/Markdent.pm called at t/markup/theory/big-table.t line 8
        main::BEGIN() called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
        eval {...} called at /usr/local/lib/perl5/site_perl/5.10.0/MooseX/StrictConstructor.pm line 11
BEGIN failed--compilation aborted at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Event/StartDocument.pm line 11.
Compilation failed in require at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Dialect/Standard/BlockParser.pm line 10.
BEGIN failed--compilation aborted at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Dialect/Standard/BlockParser.pm line 10.
Compilation failed in require at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Parser.pm line 10.
BEGIN failed--compilation aborted at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Markdent/Parser.pm line 10.
Compilation failed in require at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Test/Markdent.pm line 19.
BEGIN failed--compilation aborted at /root/.cpan/build/Markdent-0.17-ArTa2I/blib/lib/Test/Markdent.pm line 19.
Compilation failed in require at t/markup/theory/big-table.t line 8.
BEGIN failed--compilation aborted at t/markup/theory/big-table.t line 8.
t/markup/theory/big-table.t ........... Dubious, test returned 9 (wstat 2304, 0x900)

upgrading to latest MooseX::StrictConstructor fixes

**Comment by bobtfish** [comment]
Sorry, but you have completely the wrong project here.

This is test fail is for Markdent, and this is Text::MultiMarkdown.
